// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmTgVkCw0jD8TNyKqjpHUvHLV3cqcOAUg',
    appId: '1:519892758071:android:1a2d6839de128a046d59b2',
    messagingSenderId: '519892758071',
    projectId: 'flutter-coffee-and-tea-app',
    storageBucket: 'flutter-coffee-and-tea-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-rqbUqGh0UNUsRGeMe1uq-X8FAVPYO3Y',
    appId: '1:519892758071:ios:f754b1e118d02e1e6d59b2',
    messagingSenderId: '519892758071',
    projectId: 'flutter-coffee-and-tea-app',
    storageBucket: 'flutter-coffee-and-tea-app.firebasestorage.app',
    iosClientId: '519892758071-itgjgk0s45n7oksvtsd1q1lfn53vv36d.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCoffeeAndTea',
  );
}
